import { Select } from '@react-three/postprocessing'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/lock-21-mockup-2.glb --output src/components/lock-21-mockup/lock-21-mockup-2.jsx --shadows --transform --exportdefault --keepmeshes --keepmaterials --keepnames --format avif --resolution 2048 --simplify 
Files: public/lock-21-mockup-2.glb [28.03MB] > /home/user/lock21.info-react-three-fiber/src/components/lock-21-mockup/lock-21-mockup-2-transformed.glb [1.69MB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ hovered, ...props }) {
  const { nodes, materials } = useGLTF('/lock-21-mockup-2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="base_map" castShadow receiveShadow geometry={nodes.base_map.geometry} material={materials['carte Baets n/b']} position={[0.224, -0.03, 0]} scale={35.794} />
      <mesh name="mur_nord" castShadow receiveShadow geometry={nodes.mur_nord.geometry} material={materials['mur nord']} position={[0.224, 0.122, 0]} scale={35.794} />
      <mesh name="talus_nord" castShadow receiveShadow geometry={nodes.talus_nord.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.122, 0]} scale={35.794} />
      <mesh name="talus_sud" castShadow receiveShadow geometry={nodes.talus_sud.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.122, 0]} />
      <mesh name="mur_sud" castShadow receiveShadow geometry={nodes.mur_sud.geometry} material={materials['mur nord']} position={[0.224, 0.122, 0]} scale={35.794} />
      <mesh name="mockup_zone_1" castShadow receiveShadow geometry={nodes.mockup_zone_1.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_2" castShadow receiveShadow geometry={nodes.mockup_zone_2.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_3" castShadow receiveShadow geometry={nodes.mockup_zone_3.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_4" castShadow receiveShadow geometry={nodes.mockup_zone_4.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_5" castShadow receiveShadow geometry={nodes.mockup_zone_5.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_6" castShadow receiveShadow geometry={nodes.mockup_zone_6.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_7" castShadow receiveShadow geometry={nodes.mockup_zone_7.geometry} material={materials['zone 7']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_10" castShadow receiveShadow geometry={nodes.mockup_zone_10.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_11" castShadow receiveShadow geometry={nodes.mockup_zone_11.geometry} material={materials['zone 11']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_12" castShadow receiveShadow geometry={nodes.mockup_zone_12.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_13" castShadow receiveShadow geometry={nodes.mockup_zone_13.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_14" castShadow receiveShadow geometry={nodes.mockup_zone_14.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_15" castShadow receiveShadow geometry={nodes.mockup_zone_15.geometry} material={materials['carte Baets n/b']} position={[0.224, 0.152, 0]} scale={35.794} />
      <mesh name="mockup_zone_16" castShadow receiveShadow geometry={nodes.mockup_zone_16.geometry} material={materials['zone 11']} position={[0.224, 0, 0]} scale={35.794} />
      <mesh name="mockup_zone_18" castShadow receiveShadow geometry={nodes.mockup_zone_18.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0]} scale={35.794} />
      <mesh name="mockup_zone_19" castShadow receiveShadow geometry={nodes.mockup_zone_19.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0]} scale={35.794} />
      <mesh name="mockup_zone_20" castShadow receiveShadow geometry={nodes.mockup_zone_20.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0]} scale={35.794} />
      <mesh name="mockup_zone_9" castShadow receiveShadow geometry={nodes.mockup_zone_9.geometry} material={materials['carte Baets n/b']} position={[0.224, 7.285, 0]} scale={35.794} />
      <mesh name="zone_8" castShadow receiveShadow geometry={nodes.zone_8.geometry} material={materials.Material_0} position={[-53.191, 7.078, -28.542]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305} />
      <mesh name="1" castShadow receiveShadow geometry={nodes['1'].geometry} material={materials['numéro de zone']} position={[-33.594, 2.417, -32.164]} />
      <mesh name="2" castShadow receiveShadow geometry={nodes['2'].geometry} material={materials['numéro de zone']} position={[-33.594, 0.213, -23.89]} />
      <mesh name="3" castShadow receiveShadow geometry={nodes['3'].geometry} material={materials['numéro de zone']} position={[-33.594, 0.213, -15.474]} />
      <mesh name="4" castShadow receiveShadow geometry={nodes['4'].geometry} material={materials['numéro de zone']} position={[-33.594, 0.213, -6.727]} />
      <mesh name="5" castShadow receiveShadow geometry={nodes['5'].geometry} material={materials['numéro de zone']} position={[-33.594, 0.213, 1.547]} />
      <mesh name="6" castShadow receiveShadow geometry={nodes['6'].geometry} material={materials['numéro de zone']} position={[-33.594, 0.213, 10.104]} />
      <mesh name="7" castShadow receiveShadow geometry={nodes['7'].geometry} material={materials['numéro de zone']} position={[-17.761, 7.193, -37.78]} />
      <mesh name="10" castShadow receiveShadow geometry={nodes['10'].geometry} material={materials['numéro de zone']} position={[-42.968, 0.305, -32.164]} />
      <mesh name="11" castShadow receiveShadow geometry={nodes['11'].geometry} material={materials['numéro de zone']} position={[-42.628, 0.305, -24.561]} />
      <mesh name="12" castShadow receiveShadow geometry={nodes['12'].geometry} material={materials['numéro de zone']} position={[-42.778, 0.183, -15.654]} />
      <mesh name="13" castShadow receiveShadow geometry={nodes['13'].geometry} material={materials['numéro de zone']} position={[-42.526, 0.183, -7.881]} />
      <mesh name="14" castShadow receiveShadow geometry={nodes['14'].geometry} material={materials['numéro de zone']} position={[-42.641, 0.183, 0.459]} />
      <mesh name="15" castShadow receiveShadow geometry={nodes['15'].geometry} material={materials['numéro de zone']} position={[-42.667, 0.183, 8.402]} />
      <mesh name="16" castShadow receiveShadow geometry={nodes['16'].geometry} material={materials['numéro de zone']} position={[-23.805, 0.03, 10.933]} scale={0.838} />
      <mesh name="18" castShadow receiveShadow geometry={nodes['18'].geometry} material={materials['numéro de zone']} position={[-82.864, 3.383, 2.583]} />
      <mesh name="19" castShadow receiveShadow geometry={nodes['19'].geometry} material={materials['numéro de zone']} position={[-70.322, 3.383, 6.884]} />
      <mesh name="20" castShadow receiveShadow geometry={nodes['20'].geometry} material={materials['numéro de zone']} position={[-54.496, 3.383, 10.463]} />
      <mesh name="8" castShadow receiveShadow geometry={nodes['8'].geometry} material={materials['numéro de zone']} position={[-52.389, 7.393, -37.382]} />
      <mesh name="Plane" castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials['Material.010']} position={[-50.75, 0, -26.106]} />
    </group>
  )
}

useGLTF.preload('/lock-21-mockup-2-transformed.glb')
