import { Select } from "@react-three/postprocessing"

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/lock-21-mockup.glb --output src/components/lock-21-mockup/lock-21-mockup.jsx --shadows --transform --exportdefault --keepmeshes --keepmaterials --keepnames --format avif --resolution 2048 --meta 
Files: public/lock-21-mockup.glb [27.3MB] > /home/user/lock21.info-react-three-fiber/src/components/lock-21-mockup/lock-21-mockup-transformed.glb [1.83MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/lock-21-mockup-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <Select enabled={false}>
      <mesh name="base_map" castShadow receiveShadow geometry={nodes.base_map.geometry} material={materials['Empty.001']} position={[0.224, 0, -0.03]} scale={35.794} userData={{ name: 'base map' }} />
      </Select>
      <mesh name="mur_nord" castShadow receiveShadow geometry={nodes.mur_nord.geometry} material={materials['Empty.001']} position={[0.224, 0, -0.03]} scale={35.794} userData={{ name: 'mur nord' }} />
      <mesh name="talus_nord" castShadow receiveShadow geometry={nodes.talus_nord.geometry} material={materials['Empty.001']} position={[0.224, 0, -0.03]} scale={35.794} userData={{ name: 'talus nord' }} />
      <mesh name="talus_sud" castShadow receiveShadow geometry={nodes.talus_sud.geometry} material={materials['Empty.001']} position={[0.224, 0, -0.03]} scale={35.794} userData={{ name: 'talus sud' }} />
      <mesh name="mur_sud" castShadow receiveShadow geometry={nodes.mur_sud.geometry} material={materials['Empty.001']} position={[0.224, 0, -0.03]} scale={35.794} userData={{ name: 'mur sud' }} />
      <mesh name="zone_1" castShadow receiveShadow geometry={nodes.zone_1.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 1' }} />
      <mesh name="zone_2" castShadow receiveShadow geometry={nodes.zone_2.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 2' }} />
      <mesh name="zone_3" castShadow receiveShadow geometry={nodes.zone_3.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 3' }} />
      <mesh name="zone_4" castShadow receiveShadow geometry={nodes.zone_4.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 4' }} />
      <mesh name="zone_5" castShadow receiveShadow geometry={nodes.zone_5.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 5' }} />
      <mesh name="zone_6" castShadow receiveShadow geometry={nodes.zone_6.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 6' }} />
      <mesh name="zone_7" castShadow receiveShadow geometry={nodes.zone_7.geometry} material={materials['zone 7']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 7' }} />
      <mesh name="zone_10" castShadow receiveShadow geometry={nodes.zone_10.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 10' }} />
      <mesh name="zone_11" castShadow receiveShadow geometry={nodes.zone_11.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 11' }} />
      <mesh name="zone_12" castShadow receiveShadow geometry={nodes.zone_12.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 12' }} />
      <mesh name="zone_13" castShadow receiveShadow geometry={nodes.zone_13.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 13' }} />
      <mesh name="zone_14" castShadow receiveShadow geometry={nodes.zone_14.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 14' }} />
      <mesh name="zone_15" castShadow receiveShadow geometry={nodes.zone_15.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 15' }} />
      <mesh name="zone_16" castShadow receiveShadow geometry={nodes.zone_16.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 16' }} />
      <mesh name="zone_18" castShadow receiveShadow geometry={nodes.zone_18.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 18' }} />
      <mesh name="zone_19" castShadow receiveShadow geometry={nodes.zone_19.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 19' }} />
      <mesh name="zone_20" castShadow receiveShadow geometry={nodes.zone_20.geometry} material={materials['Empty.001']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'zone 20' }} />
      <mesh name="8" castShadow receiveShadow geometry={nodes['8'].geometry} material={materials['Material.002']} position={[-53.619, 38.253, 7.393]} userData={{ name: '8' }} />
      <mesh name="Plane" castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials['Material.010']} position={[-52.097, 26.977, 0]} userData={{ name: 'Plane' }} />
      <mesh name="1" castShadow receiveShadow geometry={nodes['1'].geometry} material={materials['Material.002']} position={[-33.594, 32.164, 2.264]} userData={{ name: '1' }} />
      <mesh name="2" castShadow receiveShadow geometry={nodes['2'].geometry} material={materials['Material.002']} position={[-33.594, 23.89, 0.061]} userData={{ name: '2' }} />
      <mesh name="3" castShadow receiveShadow geometry={nodes['3'].geometry} material={materials['Material.002']} position={[-33.594, 15.474, 0.061]} userData={{ name: '3' }} />
      <mesh name="4" castShadow receiveShadow geometry={nodes['4'].geometry} material={materials['Material.002']} position={[-33.594, 6.727, 0.061]} userData={{ name: '4' }} />
      <mesh name="5" castShadow receiveShadow geometry={nodes['5'].geometry} material={materials['Material.002']} position={[-33.594, -1.547, 0.061]} userData={{ name: '5' }} />
      <mesh name="6" castShadow receiveShadow geometry={nodes['6'].geometry} material={materials['Material.002']} position={[-33.594, -10.104, 0.061]} userData={{ name: '6' }} />
      <mesh name="7" castShadow receiveShadow geometry={nodes['7'].geometry} material={materials['Material.002']} position={[-17.761, 37.78, 7.041]} userData={{ name: '7' }} />
      <mesh name="10" castShadow receiveShadow geometry={nodes['10'].geometry} material={materials['Material.002']} position={[-39.434, 32.164, 7.163]} userData={{ name: '10' }} />
      <mesh name="11" castShadow receiveShadow geometry={nodes['11'].geometry} material={materials['Material.002']} position={[-39.093, 24.561, 7.163]} userData={{ name: '11' }} />
      <mesh name="12" castShadow receiveShadow geometry={nodes['12'].geometry} material={materials['Material.002']} position={[-39.244, 15.654, 7.041]} userData={{ name: '12' }} />
      <mesh name="13" castShadow receiveShadow geometry={nodes['13'].geometry} material={materials['Material.002']} position={[-38.992, 7.881, 7.041]} userData={{ name: '13' }} />
      <mesh name="14" castShadow receiveShadow geometry={nodes['14'].geometry} material={materials['Material.002']} position={[-39.107, -0.459, 7.041]} userData={{ name: '14' }} />
      <mesh name="15" castShadow receiveShadow geometry={nodes['15'].geometry} material={materials['Material.002']} position={[-39.132, -8.402, 7.041]} userData={{ name: '15' }} />
      <mesh name="16" castShadow receiveShadow geometry={nodes['16'].geometry} material={materials['Material.002']} position={[-23.805, -10.933, 0.03]} scale={0.838} userData={{ name: '16' }} />
      <mesh name="18" castShadow receiveShadow geometry={nodes['18'].geometry} material={materials['Material.002']} position={[-82.864, -2.583, 3.383]} userData={{ name: '18' }} />
      <mesh name="19" castShadow receiveShadow geometry={nodes['19'].geometry} material={materials['Material.002']} position={[-70.322, -6.884, 3.383]} userData={{ name: '19' }} />
      <mesh name="20" castShadow receiveShadow geometry={nodes['20'].geometry} material={materials['Material.002']} position={[-54.496, -10.463, 3.383]} userData={{ name: '20' }} />
      <Select enabled={true}>
      <mesh name="zone_8_-_lens_corrected_-_mesh_-_high_quality_200K_faces" castShadow receiveShadow geometry={nodes['zone_8_-_lens_corrected_-_mesh_-_high_quality_200K_faces'].geometry} material={materials.Material_0} position={[-54.538, 29.413, 7.078]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305} userData={{ name: 'zone 8 - lens corrected - mesh - high quality 200K faces' }} />
      </Select>
    </group>
  )
}

useGLTF.preload('/lock-21-mockup-transformed.glb')
