/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/lock-21-mockup-1.glb --output src/components/lock-21-mockup/lock-21-mockup-1.jsx --shadows --transform --exportdefault --keepmeshes --keepmaterials --keepnames --format avif --resolution 2048 --meta 
Files: public/lock-21-mockup-1.glb [27.4MB] > /home/user/lock21.info-react-three-fiber/src/components/lock-21-mockup/lock-21-mockup-1-transformed.glb [1.85MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/lock-21-mockup-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="base_map" castShadow receiveShadow geometry={nodes.base_map.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, -0.03]} scale={35.794} userData={{ name: 'base map' }} />
      <mesh name="mur_nord" castShadow receiveShadow geometry={nodes.mur_nord.geometry} material={materials['mur nord']} position={[0.224, 0, 0.122]} scale={35.794} userData={{ name: 'mur nord' }} />
      <mesh name="talus_nord" castShadow receiveShadow geometry={nodes.talus_nord.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.122]} scale={35.794} userData={{ name: 'talus nord' }} />
      <mesh name="talus_sud" castShadow receiveShadow geometry={nodes.talus_sud.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.122]} userData={{ name: 'talus sud' }} />
      <mesh name="mur_sud" castShadow receiveShadow geometry={nodes.mur_sud.geometry} material={materials['mur nord']} position={[0.224, 0, 0.122]} scale={35.794} userData={{ name: 'mur sud' }} />
      <mesh name="mockup_zone_1" castShadow receiveShadow geometry={nodes.mockup_zone_1.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 1' }} />
      <mesh name="mockup_zone_2" castShadow receiveShadow geometry={nodes.mockup_zone_2.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 2' }} />
      <mesh name="mockup_zone_3" castShadow receiveShadow geometry={nodes.mockup_zone_3.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 3' }} />
      <mesh name="mockup_zone_4" castShadow receiveShadow geometry={nodes.mockup_zone_4.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 4' }} />
      <mesh name="mockup_zone_5" castShadow receiveShadow geometry={nodes.mockup_zone_5.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 5' }} />
      <mesh name="mockup_zone_6" castShadow receiveShadow geometry={nodes.mockup_zone_6.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 6' }} />
      <mesh name="mockup_zone_7" castShadow receiveShadow geometry={nodes.mockup_zone_7.geometry} material={materials['zone 7']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 7' }} />
      <mesh name="mockup_zone_10" castShadow receiveShadow geometry={nodes.mockup_zone_10.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 10' }} />
      <mesh name="mockup_zone_11" castShadow receiveShadow geometry={nodes.mockup_zone_11.geometry} material={materials['zone 11']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 11' }} />
      <mesh name="mockup_zone_12" castShadow receiveShadow geometry={nodes.mockup_zone_12.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 12' }} />
      <mesh name="mockup_zone_13" castShadow receiveShadow geometry={nodes.mockup_zone_13.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 13' }} />
      <mesh name="mockup_zone_14" castShadow receiveShadow geometry={nodes.mockup_zone_14.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 14' }} />
      <mesh name="mockup_zone_15" castShadow receiveShadow geometry={nodes.mockup_zone_15.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0.152]} scale={35.794} userData={{ name: 'mockup zone 15' }} />
      <mesh name="mockup_zone_16" castShadow receiveShadow geometry={nodes.mockup_zone_16.geometry} material={materials['zone 11']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'mockup zone 16' }} />
      <mesh name="mockup_zone_18" castShadow receiveShadow geometry={nodes.mockup_zone_18.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'mockup zone 18' }} />
      <mesh name="mockup_zone_19" castShadow receiveShadow geometry={nodes.mockup_zone_19.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'mockup zone 19' }} />
      <mesh name="mockup_zone_20" castShadow receiveShadow geometry={nodes.mockup_zone_20.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 0]} scale={35.794} userData={{ name: 'mockup zone 20' }} />
      <mesh name="mockup_zone_9" castShadow receiveShadow geometry={nodes.mockup_zone_9.geometry} material={materials['carte Baets n/b']} position={[0.224, 0, 7.285]} scale={35.794} userData={{ name: 'mockup zone 9' }} />
      <mesh name="zone_8" castShadow receiveShadow geometry={nodes.zone_8.geometry} material={materials.Material_0} position={[-53.191, 28.542, 7.078]} rotation={[-Math.PI / 2, 0, 0]} scale={0.305} userData={{ name: 'zone 8' }} />
      <mesh name="1" castShadow receiveShadow geometry={nodes['1'].geometry} material={materials['numéro de zone']} position={[-33.594, 32.164, 2.417]} userData={{ name: '1' }} />
      <mesh name="2" castShadow receiveShadow geometry={nodes['2'].geometry} material={materials['numéro de zone']} position={[-33.594, 23.89, 0.213]} userData={{ name: '2' }} />
      <mesh name="3" castShadow receiveShadow geometry={nodes['3'].geometry} material={materials['numéro de zone']} position={[-33.594, 15.474, 0.213]} userData={{ name: '3' }} />
      <mesh name="4" castShadow receiveShadow geometry={nodes['4'].geometry} material={materials['numéro de zone']} position={[-33.594, 6.727, 0.213]} userData={{ name: '4' }} />
      <mesh name="5" castShadow receiveShadow geometry={nodes['5'].geometry} material={materials['numéro de zone']} position={[-33.594, -1.547, 0.213]} userData={{ name: '5' }} />
      <mesh name="6" castShadow receiveShadow geometry={nodes['6'].geometry} material={materials['numéro de zone']} position={[-33.594, -10.104, 0.213]} userData={{ name: '6' }} />
      <mesh name="7" castShadow receiveShadow geometry={nodes['7'].geometry} material={materials['numéro de zone']} position={[-17.761, 37.78, 7.193]} userData={{ name: '7' }} />
      <mesh name="10" castShadow receiveShadow geometry={nodes['10'].geometry} material={materials['numéro de zone']} position={[-42.968, 32.164, 0.305]} userData={{ name: '10' }} />
      <mesh name="11" castShadow receiveShadow geometry={nodes['11'].geometry} material={materials['numéro de zone']} position={[-42.628, 24.561, 0.305]} userData={{ name: '11' }} />
      <mesh name="12" castShadow receiveShadow geometry={nodes['12'].geometry} material={materials['numéro de zone']} position={[-42.778, 15.654, 0.183]} userData={{ name: '12' }} />
      <mesh name="13" castShadow receiveShadow geometry={nodes['13'].geometry} material={materials['numéro de zone']} position={[-42.526, 7.881, 0.183]} userData={{ name: '13' }} />
      <mesh name="14" castShadow receiveShadow geometry={nodes['14'].geometry} material={materials['numéro de zone']} position={[-42.641, -0.459, 0.183]} userData={{ name: '14' }} />
      <mesh name="15" castShadow receiveShadow geometry={nodes['15'].geometry} material={materials['numéro de zone']} position={[-42.667, -8.402, 0.183]} userData={{ name: '15' }} />
      <mesh name="16" castShadow receiveShadow geometry={nodes['16'].geometry} material={materials['numéro de zone']} position={[-23.805, -10.933, 0.03]} scale={0.838} userData={{ name: '16' }} />
      <mesh name="18" castShadow receiveShadow geometry={nodes['18'].geometry} material={materials['numéro de zone']} position={[-82.864, -2.583, 3.383]} userData={{ name: '18' }} />
      <mesh name="19" castShadow receiveShadow geometry={nodes['19'].geometry} material={materials['numéro de zone']} position={[-70.322, -6.884, 3.383]} userData={{ name: '19' }} />
      <mesh name="20" castShadow receiveShadow geometry={nodes['20'].geometry} material={materials['numéro de zone']} position={[-54.496, -10.463, 3.383]} userData={{ name: '20' }} />
      <mesh name="8" castShadow receiveShadow geometry={nodes['8'].geometry} material={materials['numéro de zone']} position={[-52.389, 37.382, 7.393]} userData={{ name: '8' }} />
      <mesh name="Plane" castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials['Material.010']} position={[-50.75, 26.106, 0]} userData={{ name: 'Plane' }} />
    </group>
  )
}

useGLTF.preload('/lock-21-mockup-1-transformed.glb')
